# Generated by Django 3.2.19 on 2023-05-30 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cultivo',
            fields=[
                ('idCultivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('idImage', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='blog/images/')),
            ],
        ),
        migrations.CreateModel(
            name='parrafo',
            fields=[
                ('idParrafo', models.AutoField(primary_key=True, serialize=False)),
                ('parrafo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='perdida',
            fields=[
                ('idPerdida', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadGrano', models.FloatField()),
                ('cantidadMonetaria', models.FloatField()),
                ('fechaPerdida', models.DateField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='precipitacion',
            fields=[
                ('idPrecipitacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='produccion',
            fields=[
                ('idProduccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadProduccion', models.FloatField()),
                ('fechaProduccion', models.DateField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='temperaturas',
            fields=[
                ('idTemperatura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('grados', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='seccion',
            fields=[
                ('idSeccion', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.imagen')),
                ('parrafo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.parrafo')),
                ('perdida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.perdida')),
                ('precipitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.precipitacion')),
                ('produccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.produccion')),
                ('temperaturas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.temperaturas')),
            ],
        ),
    ]
