# Generated by Django 3.2.19 on 2023-05-30 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seccion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.imagen'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='parrafo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.parrafo'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='perdida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.perdida'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='precipitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.precipitacion'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.produccion'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='temperaturas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.temperaturas'),
        ),
    ]
