# Generated by Django 3.2.19 on 2023-05-30 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230529_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='perdida',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='produccion',
        ),
        migrations.AddField(
            model_name='seccion',
            name='cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.cultivo'),
        ),
    ]
